/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import boundaries.CourseQueryParams;
import controllers.AbstractController;
import controllers.ICourseCatalogController;
import javax.swing.JTable;

/**
 *
 * @author astahlman
 */
public class CourseCatalogUserInterface extends AbstractUserInterface {

    private ICourseCatalogController controller;
    private JTable table;
    
    /**
     * Creates new form CourseCatalogUserInterface
     */
    public CourseCatalogUserInterface(ICourseCatalogController controller) {
        this.controller = controller;
        initComponents();
    }

    
    @Override
    public void setController(AbstractController controller)
    {
        this.controller = (ICourseCatalogController) controller;
    }
    
    @Override
    public AbstractController getController()
    {
        return (AbstractController) this.controller;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        nameRadio = new javax.swing.JRadioButton();
        crnRadio = new javax.swing.JRadioButton();
        departmentRadio = new javax.swing.JRadioButton();
        scrollPane = new javax.swing.JScrollPane();

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(nameRadio);
        nameRadio.setText("Name");

        buttonGroup1.add(crnRadio);
        crnRadio.setText("CRN");

        buttonGroup1.add(departmentRadio);
        departmentRadio.setText("Department");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(nameRadio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(crnRadio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(departmentRadio))
                    .add(layout.createSequentialGroup()
                        .add(searchTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 309, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(searchButton)))
                .add(22, 22, 22))
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(scrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 440, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(searchButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameRadio)
                    .add(crnRadio)
                    .add(departmentRadio))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
           String searchExp = searchTextField.getText();
        if (!searchExp.isEmpty())
        {
            CourseQueryParams query = new CourseQueryParams();
            if (nameRadio.isSelected())
            {
                query.setName(searchExp);
            }
            else if (crnRadio.isSelected())
            {
                query.setCRN(searchExp);
            }
            else
            {
                query.setDepartment(searchExp);
            }
            this.controller.doQuery(query);
        }
        else
        {
            this.showAlert(this, "Must enter search params");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton crnRadio;
    private javax.swing.JRadioButton departmentRadio;
    private javax.swing.JRadioButton nameRadio;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
