/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.AbstractController;
import controllers.IMainHubController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author astahlman
 */
public class MainHubUserInterface extends AbstractUserInterface {

    private IMainHubController controller;
    /**
     * Creates new form MainHubUserInterface
     */
    public MainHubUserInterface(IMainHubController controller) {
        initComponents();
        
        this.controller = controller;
        ActionListener buttonListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                handleButtonClicked(evt.getActionCommand());
            };
        };
        
        loginButton.addActionListener(buttonListener);
        viewScheduleButton.addActionListener(buttonListener);
        viewEnrollmentSummaryButton.addActionListener(buttonListener);
        searchCatalogButton.addActionListener(buttonListener);
        addCourseButton.addActionListener(buttonListener);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        loginButton = new javax.swing.JButton();
        viewScheduleButton = new javax.swing.JButton();
        searchCatalogButton = new javax.swing.JButton();
        viewEnrollmentSummaryButton = new javax.swing.JButton();
        addCourseButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 400));

        loginButton.setText("Logout");

        viewScheduleButton.setText("View Schedule");

        searchCatalogButton.setText("Search Catalog");

        viewEnrollmentSummaryButton.setText("View Enrollment Summary");

        addCourseButton.setText("Add Course");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(loginButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(addCourseButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(searchCatalogButton)
                            .add(viewScheduleButton)))
                    .add(viewEnrollmentSummaryButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(loginButton)
                    .add(searchCatalogButton))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addCourseButton)
                    .add(viewScheduleButton))
                .add(18, 18, 18)
                .add(viewEnrollmentSummaryButton)
                .addContainerGap(255, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void handleButtonClicked(String actionCommand)
    {
        this.controller.launchController(actionCommand);       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseButton;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton searchCatalogButton;
    private javax.swing.JButton viewEnrollmentSummaryButton;
    private javax.swing.JButton viewScheduleButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the controller
     */
    @Override
    public AbstractController getController() {
        return (AbstractController) controller;
    }

    /**
     * @param controller the controller to set
     */
    @Override
    public void setController(AbstractController controller) {
        this.controller = (IMainHubController) controller;
    }
}
